server:
  port: ${PORT:8087}
  servlet:
      context-path: ${CONTEXT_PATH:/dynamodbcrud}


spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:"@spring.profiles.active@"}
  application:
    name: ${APP_NAME:crud-dynamodb}
